# frozen_string_literal: true
source 'https://supermarket.chef.io'

cookbook 'sshd', '~> 1.3.1'
cookbook "bootstrap",  git: "https://github.com/CloudAssessments/chef-bootstrap.git"
cookbook 'nodejs', '= 2.0.0'
