# frozen_string_literal: true
source 'https://supermarket.chef.io'

metadata
cookbook 'sshd', '~> 1.3.1'
cookbook "bootstrap",  git: "https://github.com/CloudAssessments/chef-bootstrap.git"
cookbook "lfcs", "machinist", git: "https://github.com/CloudAssessments/chef-lfcs.git" 
