# frozen_string_literal: true
source 'https://supermarket.chef.io'

metadata
cookbook 'postgresql', '~> 6.1.1'
cookbook 'openssl', '~> 7.1.0'
cookbook 'sshd', '~> 1.3.1'
cookbook 'cloudcli', '~> 1.2.0'
cookbook "bootstrap",  git: "https://github.com/CloudAssessments/chef-bootstrap.git"

